"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.ItemPage = ItemPage;
const jsx_runtime_1 = require("react/jsx-runtime");
const react_1 = __importDefault(require("react"));
function ItemPage({ item }) {
    return ((0, jsx_runtime_1.jsxs)("section", { className: "mx-auto grid max-w-6xl grid-cols-1 gap-6 px-4 py-6 lg:grid-cols-2", children: [(0, jsx_runtime_1.jsxs)("div", { className: "space-y-3", children: [(0, jsx_runtime_1.jsx)("img", { src: item.previewUrls[0], alt: item.title, className: "h-80 w-full rounded-2xl object-cover" }), (0, jsx_runtime_1.jsx)("div", { className: "grid grid-cols-2 gap-3", children: item.previewUrls.slice(1).map((url) => ((0, jsx_runtime_1.jsx)("img", { src: url, alt: item.title, className: "h-36 w-full rounded-xl object-cover" }, url))) })] }), (0, jsx_runtime_1.jsxs)("div", { className: "space-y-5", children: [(0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsxs)("p", { className: "text-sm text-zinc-500", children: [item.seller.displayName, " \u00B7 ", item.seller.handle] }), (0, jsx_runtime_1.jsx)("h1", { className: "text-2xl font-bold text-zinc-900", children: item.title }), (0, jsx_runtime_1.jsx)("p", { className: "mt-2 text-zinc-600", children: item.description })] }), (0, jsx_runtime_1.jsxs)("div", { className: "rounded-xl border border-zinc-200 p-4", children: [(0, jsx_runtime_1.jsx)("p", { className: "text-sm font-semibold", children: "Originality" }), (0, jsx_runtime_1.jsx)("p", { className: "mt-1 text-sm text-zinc-700", children: item.originalityStatus.replace('_', ' ') })] }), (0, jsx_runtime_1.jsxs)("div", { className: "rounded-xl border border-zinc-200 p-4", children: [(0, jsx_runtime_1.jsx)("p", { className: "text-sm font-semibold", children: "Metadata" }), (0, jsx_runtime_1.jsx)("pre", { className: "mt-2 overflow-auto text-xs text-zinc-700", children: JSON.stringify(item.metadata, null, 2) })] }), item.reviews.length > 0 && ((0, jsx_runtime_1.jsxs)("div", { className: "rounded-xl border border-zinc-200 p-4", children: [(0, jsx_runtime_1.jsx)("p", { className: "text-sm font-semibold", children: "Delivered Reviews" }), (0, jsx_runtime_1.jsx)("ul", { className: "mt-2 space-y-2 text-sm text-zinc-700", children: item.reviews.map((review) => ((0, jsx_runtime_1.jsxs)("li", { children: [review.reviewerName, " \u00B7 ", review.rating, "/5 \u00B7 ", review.comment] }, review.id))) })] })), (0, jsx_runtime_1.jsxs)("button", { type: "button", className: "w-full rounded-xl bg-zinc-900 px-4 py-3 font-medium text-white transition hover:bg-zinc-700", children: ["Buy for TRY ", item.price] })] })] }));
}
//# sourceMappingURL=ItemPage.js.map